# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:

    macos:
      xcode: 12.0.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run:
          name: テスト
          command: |
            pod install;
            xcodebuild -workspace mySample.xcworkspace -scheme "mySampleTests" -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.0' test;
      - run:
          name: ダミー アーティファクトの作成
          command: |
            mkdir uploadDir;
            echo "my artifact files in a dir" > uploadDir/sample.txt;
      - store_artifacts:
          path: build
  aaa:
    macos:
      xcode: 12.0.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run:
          name: 成果物ビルド
          command: |
            echo hello!!!


workflows:
  version: 2.1
  build:
    jobs:
      - build
